### PR TITLE
add 1 decimal place to formatting

### LINKED ISSUE #11: Add decimal percent option
Allow for overlay to show decimals ie 75.4
Would help with rounding issues.
Often with percent thresholds with rounding can be confusing.
If some transition happens at 60% the overlay will show 60% even if it is 60.1 -> 60.4, can be a bit confusing.

Otherwise, could have an option to always round up instead of down.

### PR DESCRIPTION
**Pull request by thejdubs**
closes #11 
without option version

### CODE REVIEW

**Comment by thejdubs** [comment]
wrote 2 commits,
one with config option, one as just the default
let me know which one you prefer

**Comment by lejeffe** [comment]
Before i add it, have you tested it yourself.

**Comment by lejeffe** [comment]
I would prefer to let the user choose to add the decimal or not, but have this on by default. Can you make this happen? Limited on time at the moment.

**Comment by thejdubs** [comment]
hmm after some more testing, I don't think it actually adds too much value. 
Since we only get the hp bar length value to determine the percentage most are inaccurate (comparing with the in game which uses true value).
Also the increased precision will only even be really helpful with larger hp bars. 
Think i might scrap it. Let me know what you think.

**Comment by lejeffe** [comment]
> 

It could prove use full within ToA as these npc's have more detailed hp bars. But this would need further testing to actually know if it adds anything

**Comment by thejdubs** [comment]
yea thats where i was doing my testing.
akkha's health bar doesnt provide any more precision
zebak's provides a bit more, but the numbers arent fully accurate when comparing to the in game percents

**Pull request closed without merging**
